name: bluez
version: 5.53-11-dev
type: app
summary: Bluetooth tools and daemons
description: |
 This package contains tools and system daemons for using Bluetooth
 devices. BlueZ is the official Linux Bluetooth protocol stack. It
 is an Open Source project distributed under GNU General Public
 License (GPL). See the project homepage for more details:
 https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
confinement: strict
grade: stable
base: core20

layout:
  /usr/var/lib/bluetooth:
    symlink: $SNAP_DATA
  /usr/etc/bluetooth:
    symlink: $SNAP_DATA/etc

apps:
  bluetoothctl:
    command: bin/client-wrapper usr/bin/bluetoothctl
    plugs: [client, uhid]
  obexctl:
    command: bin/client-wrapper usr/bin/obexctl
    plugs: [client]
  bluez:
    command: bin/bluetoothd-wrapper
    daemon: simple
    slots: [service]
    plugs: [uhid, uinput, kernel-crypto-api]
  obex:
    command: "usr/lib/bluetooth/obexd"
    daemon: simple
    slots: [service]
  hciconfig:
    command: usr/bin/hciconfig
    plugs: [bluetooth-control]
  hcidump:
    command: usr/bin/hcidump
    plugs: [bluetooth-control, network-control, home]
  hciattach:
    command: usr/bin/hciattach
    plugs: [bluetooth-control]
  btattach:
    command: usr/bin/btattach
    plugs: [bluetooth-control]
  hcitool:
    command: usr/bin/hcitool
    plugs: [bluetooth-control]
  sdptool:
    command: usr/bin/sdptool
    plugs: [client]
  btmon:
    command: usr/bin/btmon
    plugs: [bluetooth-control, network-control, home]
  btmgmt:
    command: usr/bin/btmgmt
    plugs: [bluetooth-control, network-control]
  meshctl:
    command: usr/bin/meshctl
    plugs: [bluetooth-control, network-control]

plugs:
  client:
      interface: bluez

slots:
  service:
      interface: bluez

parts:

  bluez-common:
    plugin: dump
    source: bin/
    organize:
      client-wrapper: bin/client-wrapper
      bluetoothd-wrapper: bin/bluetoothd-wrapper

  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"
    organize:
      ChangeLog: snap/ChangeLog

  # Get aux scripts so they can be used in other parts. Also, stage
  # packages we rebuild later to get copyright and ensure they are in
  # the manifest.
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
      - dpkg-dev
      - git
    stage-packages:
      - bluez
      - bluez-obexd
      - bluez-hcidump
    override-build: |
      set -ex
      find "$SNAPCRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/bluez*' \
           -delete
      find "$SNAPCRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$SNAPCRAFT_PART_INSTALL"/build-tools
    prime:
      - usr/share/doc/bluez
      - usr/share/doc/bluez-obexd
      - usr/share/doc/bluez-hcidump

  bluez:
    after: [ stack-snaps-tools ]
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/bluez
    source-type: git
    source-branch: applied/ubuntu/focal-updates
    autotools-configure-parameters:
      - --prefix=/usr
      - --libexec=/usr/lib/
      - --enable-experimental
      - --enable-threads
      - --disable-cups
      - --enable-obex
      - --disable-systemd
      - --disable-silent-rules
      - --enable-test
      - --enable-deprecated
      - --enable-mesh
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS='-O2 -Wl,-z,relro,-z,now -pie -fpie'
    build-packages:
      - flex
      - bison
      - libdbus-glib-1-dev
      - libglib2.0-dev
      - libcap-ng-dev
      - udev
      - libudev-dev
      - libreadline-dev
      - libical-dev
      - libjson-c-dev
      - check
    prime:
      - usr/lib/bluetooth/bluetoothd
      - usr/lib/bluetooth/obexd
      - usr/bin/bluetoothctl
      - usr/bin/obexctl
      - usr/bin/hciconfig
      - usr/bin/hcidump
      - usr/bin/hciattach
      - usr/bin/btattach
      - usr/bin/hcitool
      - usr/bin/sdptool
      - usr/bin/btmon
      - usr/bin/btmgmt
      - usr/bin/meshctl
    override-build: |
      set -ex
      "$SNAPCRAFT_STAGE"/build-tools/check-versions bluez yes
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/patch/*
      snapcraftctl build
      cp tools/btmgmt "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      cp tools/obexctl "$SNAPCRAFT_PART_INSTALL"/usr/bin/
      # Run all tests shiped by default
      #make check
      # Strip binaries
      find "$SNAPCRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-.*executable\|application/x-.*sharedlib' | cut -d: -f1 | xargs strip
